---
- name: Install Docker
  ansible.builtin.include_tasks: frog_docker.yml
  tags:
    - docker

- name: Setup base system
  ansible.builtin.include_tasks: base_system.yml
  tags:
    - base_system

- name: Copy dotfiles
  ansible.builtin.include_tasks: dot_files.yml
  tags:
    - dot_files
